### ISSUE TITLE
New `example-c` docs work to "Test the BMI" but breaks with pymt.models 

### ISSUE THREAD

**Issue by aufdenkampe** [csdms/babelizer#102]
@mcflugen & @mdpiper,

Thank you for merging this PR!
- #97

I was able to successfully (on a Mac) follow the [Example: Wrapping a C model](https://babelizer.readthedocs.io/en/latest/example-c.html) down to the [Test the BMI](https://babelizer.readthedocs.io/en/latest/example-c.html#test-the-bmi) section, but after that I got numerous errors, all related to [pymt](https://pymt.readthedocs.io/en/latest/).

To make it work, I had to create a conda environment that built babelizer from the head of your `develop` branch, using this: https://github.com/LimnoTech/babelizer-examples/blob/main/environment.yml.

Given that pymt hasn't been updated since 2021, it might make sense to just put a big warning above that section of the docs, saying that pymt functionality is not currently compatible with the babelizer toolchain. That seems like a quick way to help folks avoid headaches.

@Volk3rJ & @ptomasula, can you try this workflow on Windows, down to Test the BMI](https://babelizer.readthedocs.io/en/latest/example-c.html#test-the-bmi)? Please do it from my modified [environment.yml](https://github.com/LimnoTech/babelizer-examples/blob/main/environment.yml) in https://github.com/LimnoTech/babelizer-examples

**Comment by mdpiper** [comment]
We just need to update *pymt*; it's 1) not built for Python 3.12, and 2) incompatible with recent changes to *gimli.units*.

**Comment by aufdenkampe** [comment]
Moving conversation on updating _pymt_ to:
- https://github.com/csdms/pymt/issues/167#issuecomment-2061707187

and closing here, as the `example-c` works well (on Mac) up to that point.
