### ISSUE TITLE
Demonstrate babelizing for all supported languages

### ISSUE THREAD

**Issue by mdpiper** [csdms/babelizer#32]
We have an [example](https://babelizer.readthedocs.io/en/latest/example.html) of babelizing a model written in C and importing it into pymt. There should also be examples for

- [ ] C++
- [ ] Fortran
- [ ] Python

to cover all the languages supported by the *babelizer*, since each language has its own subtleties.

**Comment by samharrison7** [comment]
I'd be happy to contribute a Fortran example, if that's helpful? It would basically be the same as the C example but with a few little tweaks to make it Fortran specific.

**Comment by mdpiper** [comment]
> I'd be happy to contribute a Fortran example, if that's helpful? It would basically be the same as the C example but with a few little tweaks to make it Fortran specific.

@samharrison7 That would be wonderful, thank you!
