### ISSUE TITLE
Black CI fails automatically on rendered component

### ISSUE THREAD

**Issue by mdpiper** [csdms/babelizer#48]
The *black* CI task checks all Python files, including those in the `docs` directory, of a rendered component. The `conf.py` file of a rendered component currently fails out of the box, so it should be formatted.

The problem may be larger, though; the `conf.py` file contains jinja template variables, and because *black* changes indentation based on line length, running *black* after substituting for these variables may still cause the CI test in the rendered component to fail.

**Comment by mdpiper** [comment]
@mcflugen I can fix this by removing the HTMLHelp and LaTeX options from the `conf.py` file. We don't use them. What do you think?

**Comment by mcflugen** [comment]
@mdpiper when the *babelizer* renders a project, it runs *isort* and *black* on the rendered project. I’m not sure why *black* would fail on a file that it just reformatted.

Since we don’t use the HTMLHelp and LaTeX options, we should probably remove them (but not because it fixes this issue).

**Comment by mdpiper** [comment]
@mcflugen I see now. I'll leave `conf.py` unchanged, but add it to the list of files to fix in the *render* module.

**Comment by mcflugen** [comment]
Ah, well that explains it. Thanks @mdpiper!
