### ISSUE TITLE
JOSS review: Readme suggestions 

### ISSUE THREAD

**Issue by lheagy** [csdms/babelizer#50]
These are a few suggestions for the README + intro page on the docs as a part of the JOSS review (openjournals/joss-reviews#3344). The README has a great, easy to follow set of instructions for installation! What I think could be improved though is the description of the package and who should be using it (e.g. to satisfy the "Statement of need" requirement in the JOSS documentation checklist). I appreciate it is a part of the larger CSDMS workbench, so a bit more context in the high level summary on where this project fits would be helpful for users to get a sense of if they are in the right place or if they should be looking at another repository in the CSDMS ecosystem. The summary in the paper is a good overview!

**Comment by mdpiper** [comment]
Hi @lheagy -- @mcflugen attempted to address this issue in #57. (It may be easier to view the resulting [README.rst](https://github.com/csdms/babelizer/blob/develop/README.rst) in the *develop* branch.) Please let us know if these changes satisfy the concerns raised in this issue.

**Comment by mdpiper** [comment]
Fixed with #57.
