### ISSUE TITLE
JOSS review: API documentation 

### ISSUE THREAD

**Issue by lheagy** [csdms/babelizer#52]
The [cli module](https://babelizer.readthedocs.io/en/latest/api/babelizer.html) is well documented, but the other modules are a bit sparse -- I suspect most users will be interacting through the cli, so this is the most important part, but even short descriptions associated with the rest or the public API would be nice to help with a picture of what can be accomplished with `babelizer` 

linking with openjournals/joss-reviews#3344

**Comment by mdpiper** [comment]
Hi @lheagy! I have a candidate PR (#55) to fix this issue. The docs are [here](https://babelizer.readthedocs.io/en/mdpiper-fix-52/api/babelizer.html). Please let me know what you think!
