### ISSUE TITLE
Error compiling C/C++/Fortran projects with Python 3.8 on Linux

### ISSUE THREAD

**Issue by mcflugen** [csdms/babelizer#73]
We get the following error when compiling a C, C++, or Fortran babelized project with Python 3.8 on Linux,
```bash
/usr/share/miniconda/envs/test/compiler_compat/ld: cannot find /lib64/libpthread.so.0
/usr/share/miniconda/envs/test/compiler_compat/ld: cannot find /usr/lib64/libpthread_nonshared.a
```
As described on [StackOverflow](https://stackoverflow.com/questions/71340058/conda-does-not-look-for-libpthread-and-libpthread-nonshared-at-the-right-place-w), this is a result of our babelized projects specifying a build-system in *pyproject.toml*. The requirements listed in the build-system section are installed from PyPI with *pip* but, unfortunately, these requirements are incompatible with the *conda* compilers.

**Comment by mcflugen** [comment]
#72 fixes this issue in our continuous integration tests. The fix is to first install the build-system with *conda* and then *pip*-install the project. That is,
```bash
$ mamba install cython numpy setuptools wheel
```
and then when installing the babelized project,
```bash
$ pip install -e . --no-build-isolation
```

**Comment by mdpiper** [comment]
Closing with https://github.com/csdms/babelizer/commit/c3c567498735e51f73a4045f2b33e79aa5e85b4b and with #90.
